"""empty message

Revision ID: 04109d9757eb
Revises: 
Create Date: 2019-03-05 16:31:35.325071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04109d9757eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('created_on', sa.String(length=30), nullable=True),
    sa.Column('img', sa.String(length=80), nullable=True)
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
